### ISSUE TITLE
has the callback api been tested?

### ISSUE THREAD

**Issue by c-cube** [zshipko/ocaml-rs#12]
I described a problem I have in [ocaml's forum](https://discuss.ocaml.org/t/storing-an-ocaml-value-in-a-c-structure/3521), at first glance related to global roots. But the bug persists without storing values in rust, and still manifests itself as an infinite loop in the GC. Looking at the gdb trace it looks like the gc is stuck when marking local roots. Is this part of the API tested by anyone?

**Comment by zshipko** [comment]
What version are you using? If you haven't already, try using the `master` branch.

This is most likely related to #10, I encountered similar behavior while working on that issue. There are many new updates that just need a little more testing but I hope to publish an updated version of `ocaml-rs` to crates.io sometime next week.

I'd be happy to take a look at the code if it's publicly available!

**Comment by c-cube** [comment]
The master branch doesn't compile for me (I could be wrong, I tried briefly). The branch is https://github.com/c-cube/batsat-ocaml/tree/wip-theory and it's triggered by `make test` or, after `make test` has run once, to get a stacktrace:

```
gdb --args ./_build/default/src/sudoku/sudoku_solve.exe -d 1 tests/sudoku/sudoku.txt
```

**Comment by zshipko** [comment]
Yeah sorry, just saw that the master branch was broken - it should be working now.

I will see if I can debug your code sometime over the weekend or early next week.

**Comment by zshipko** [comment]
Sorry for the slow reply. Over the weekend I updated your branch to use the current master and it seems to be working (at least the test in completing). My changes are published here: https://github.com/zshipko/batsat-ocaml/tree/wip-theory

Let me know if that's working for you, if not I can keep debugging.

**Comment by c-cube** [comment]
it still fails for me, but I forgot to add that before running tests, `opam install iter containers` is required to run the part that fails (it should display a sudoku grid, freeze, then error out)

**Comment by zshipko** [comment]
Unfortunately, I haven't had much time to debug this.

I've found that these lines are causing problems with the OCaml GC - somehow these values aren't being registered correctly: https://github.com/c-cube/batsat-ocaml/blob/wip-theory/src/lib.rs#L124 and https://github.com/c-cube/batsat-ocaml/blob/wip-theory/src/lib.rs#L133

Where are `Theory::partial_check` and `Theory::final_check` being called?

**Comment by c-cube** [comment]
They're called inside the rust code inside `solve`. I'll take another look, it's possible that it's just these custom blocks not being declared as local roots?

**Comment by c-cube** [comment]
I tried to use `caml_local!` on this local custom block, didn't fix it (but I don't remember which version of ocaml-rs it was, probably a released one)

**Comment by XVilka** [comment]
Is this still a problem?

**Comment by zshipko** [comment]
I’m not sure if this particular issue was resolved, but I have done some work to validate allocations since this this ticket was opened.

I haven’t run into any problems personally, but maybe if you have a more complex application you will uncover some edge cases. If that happens then open an issue and I’d be happy to help debug!

**Comment by c-cube** [comment]
I have no idea, the branch is dead for now, but the repro might still work?

**Comment by zshipko** [comment]
A lot of this has been rewritten in `0.10`, I've also included a test in `test/src/callback.rs` that calls a callback stored in a struct.
